[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-space-wallpaper
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-space-wallpaper
GtkTheme=oomox-space-wallpaper
IconTheme=oomox-space-wallpaper
MetacityTheme=oomox-space-wallpaper
